version: '3.8'
services:
    db:
        image: postgres:13
        environment:
            POSTGRES_DB: ${DB_USER}
            POSTGRES_USER: ${DB_NAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - '5432:5432'
        networks:
            - app-network
        volumes:
            - postgres-data:/var/lib/postgresql/data

    api:
        build: .
        depends_on:
            - db
        ports:
            - '8080:8080'
        networks:
            - app-network
        environment:
            - DB_HOST: db
            - DB_PORT: 5432
            - DB_NAME: ${DB_NAME}
            - DB_USER: ${DB_USER}
            - DB_PASSWORD: ${DB_PASSWORD}

networks:
    app-network:
        driver: bridge

volumes:
    postgres-data:
        driver: local
